/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiTranscribeClassRouteImport } from './routes/api/transcribe-class'
import { Route as AppStudyRouteImport } from './routes/_app/study'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppExamRouteImport } from './routes/_app/exam'
import { Route as AppConversionRouteImport } from './routes/_app/conversion'
import { Route as AppClassesRouteImport } from './routes/_app/classes'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiTranscribeClassRoute = ApiTranscribeClassRouteImport.update({
  id: '/api/transcribe-class',
  path: '/api/transcribe-class',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudyRoute = AppStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppExamRoute = AppExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AppRoute,
} as any)
const AppConversionRoute = AppConversionRouteImport.update({
  id: '/conversion',
  path: '/conversion',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/classes': typeof AppClassesRoute
  '/conversion': typeof AppConversionRoute
  '/exam': typeof AppExamRoute
  '/notes': typeof AppNotesRoute
  '/study': typeof AppStudyRoute
  '/api/transcribe-class': typeof ApiTranscribeClassRoute
}
export interface FileRoutesByTo {
  '/classes': typeof AppClassesRoute
  '/conversion': typeof AppConversionRoute
  '/exam': typeof AppExamRoute
  '/notes': typeof AppNotesRoute
  '/study': typeof AppStudyRoute
  '/api/transcribe-class': typeof ApiTranscribeClassRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/classes': typeof AppClassesRoute
  '/_app/conversion': typeof AppConversionRoute
  '/_app/exam': typeof AppExamRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/study': typeof AppStudyRoute
  '/api/transcribe-class': typeof ApiTranscribeClassRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classes'
    | '/conversion'
    | '/exam'
    | '/notes'
    | '/study'
    | '/api/transcribe-class'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/classes'
    | '/conversion'
    | '/exam'
    | '/notes'
    | '/study'
    | '/api/transcribe-class'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/classes'
    | '/_app/conversion'
    | '/_app/exam'
    | '/_app/notes'
    | '/_app/study'
    | '/api/transcribe-class'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiTranscribeClassRoute: typeof ApiTranscribeClassRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/transcribe-class': {
      id: '/api/transcribe-class'
      path: '/api/transcribe-class'
      fullPath: '/api/transcribe-class'
      preLoaderRoute: typeof ApiTranscribeClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/study': {
      id: '/_app/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AppStudyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exam': {
      id: '/_app/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AppExamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversion': {
      id: '/_app/conversion'
      path: '/conversion'
      fullPath: '/conversion'
      preLoaderRoute: typeof AppConversionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClassesRoute: typeof AppClassesRoute
  AppConversionRoute: typeof AppConversionRoute
  AppExamRoute: typeof AppExamRoute
  AppNotesRoute: typeof AppNotesRoute
  AppStudyRoute: typeof AppStudyRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClassesRoute: AppClassesRoute,
  AppConversionRoute: AppConversionRoute,
  AppExamRoute: AppExamRoute,
  AppNotesRoute: AppNotesRoute,
  AppStudyRoute: AppStudyRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiTranscribeClassRoute: ApiTranscribeClassRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
